[global]
api_key = "..."
# Specify the which cascade you're using apptest or prod
platform = "apptest"

[sitemap]
cascade_site = "www.csi.edu"
# path to a CSV file output from the index block
csv_path = "./sitemap.csv"
# specify target asset type folder, page, site, etc
asset_type = "page"

[image_rename]
cascade_site = "www.csi.edu"
root_folder_path = "_files/images"
within_percent=20
# resolution in [width]x[height] format
target_dimensions="1920x400"
new_folder_name="old impact images"

[press_script]
cascade_site = "www.csi.edu"
post_folder_path = "dev-misc"
file_types = "page"

[xml_edit]
cascade_site = "www.csi.edu"
new_asset_path = "_widgets/recreation-center/ski-swap"
target_page_path = "dev-misc/test"
search_path = "page-content/right-column/widget"
asset_type = "page"

[programs_creation]
# path to a CSV file with columns: [folder name, display name/title]
rename_csv_path = "./programs_creation/programs_rename.csv"
# parent folder path to create the new program folders under
root_folder_path = "programs3"
sitename = "wwwdev.csi.edu"